replicaCount: 1

image:
  repository: postgres:10
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  name: db
  port: 5432
  targetPort: 5432
deployment: 
  name: postgres
container:
  name: postgres
  port: 5432
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

dbcredentials:
  dbName: POSTGRES_USER
  dbnameValue: "postgres"
  dbPassword: POSTGRES_PASSWORD
  dbPasswordvalue: "postgres"
